parameters:
  path: ''
  job1: ''
  condition: ''

jobs:
- job: ${{ parameters.job1 }}
  pool:
    vmImage: 'macOS-10.15'
    cancelTimeoutInMinutes: 1
  dependsOn: init_macos
  condition: ${{ parameters.condition }}
  variables:
    path: ${{ parameters.path }}
  steps:
  - template: install-setup.yml

  - bash: |
      cd macports-ports
      # Checkouts BOOST 1.77.0
      git checkout eb2061a849aad5d7aabc50678231218d0d8b39cf
      cd devel/boost
      # Patches build config to optimize build time.
      patch -p0 < $(System.DefaultWorkingDirectory)/.azure/macos/Portfile-boost.diff
      sudo port install -- -no_static -python27
      git stash
    displayName: 'Build BOOST'

  - bash: |
      cd macports-ports
      # Checkouts QREncode 3.4.4
      git checkout 36419b9f5523163c9da02c704b02e53928098b86
      cd graphics/qrencode
      sudo port install
    displayName: 'Build QREncode'

  - bash: |
      cd macports-ports
      # Checkouts BDB4.8
      git checkout 3ffdb59362a83f6e77f885f64cb06b4344e485b3
      cd databases/db48
      sudo port install
    displayName: 'Build BDB4.8'

  - bash: |
      cd macports-ports
      # Checkouts OpenSSL 1.1.1k
      git checkout 332430a8a0cda7019f91238652888612a482a71a
      cd devel/openssl
      sudo port install
    displayName: 'Build OpenSSL'

  - bash: |
      cd macports-ports
      # Checkouts MiniUPNPC 1.9
      git checkout 2f4c992b8ab04cb94b48a9ee07eb3f86220ae598
      cd net/miniupnpc
      sudo port install
    displayName: 'Build MiniUPNPC'

  - bash: |
      sudo port install qt5-qtbase qt5-qttools qt5-qttranslations qt5-qtsvg
    displayName: 'Install Qt5'

  - bash: |
      tar cvfz toolkit.tar.gz /opt/local
      ls -la toolkit.tar.gz
    displayName: 'Pack MacOS Toolkit'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish MacOS Toolkit'
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/toolkit.tar.gz'
      artifactName: $(macos.toolkit.name)
